// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPLV0Hd5zWOzteRk3ZjWuOMI4UAqB5gCM',
    appId: '1:986774087079:web:0a1b951141ae1c5a53c282',
    messagingSenderId: '986774087079',
    projectId: 'by-urban',
    authDomain: 'by-urban.firebaseapp.com',
    databaseURL: 'https://by-urban-default-rtdb.firebaseio.com',
    storageBucket: 'by-urban.appspot.com',
    measurementId: 'G-Q4C8XV145D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3ZlinZq0YjOvSsfFnHylkKF96EeZYbCk',
    appId: '1:986774087079:android:b98f337fc8acd8cb53c282',
    messagingSenderId: '986774087079',
    projectId: 'by-urban',
    databaseURL: 'https://by-urban-default-rtdb.firebaseio.com',
    storageBucket: 'by-urban.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApRhsWBK0DHNxNZPknbywhuwyCDDZk2AA',
    appId: '1:986774087079:ios:9642be0b7e37364853c282',
    messagingSenderId: '986774087079',
    projectId: 'by-urban',
    databaseURL: 'https://by-urban-default-rtdb.firebaseio.com',
    storageBucket: 'by-urban.appspot.com',
    iosBundleId: 'com.example.urbanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApRhsWBK0DHNxNZPknbywhuwyCDDZk2AA',
    appId: '1:986774087079:ios:09147c81e2a6057553c282',
    messagingSenderId: '986774087079',
    projectId: 'by-urban',
    databaseURL: 'https://by-urban-default-rtdb.firebaseio.com',
    storageBucket: 'by-urban.appspot.com',
    iosBundleId: 'com.example.urbanApp.RunnerTests',
  );
}
